---
name: PR Check

on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  lint-build-test:
    uses: wisemen-digital/devops-github-actions/.github/workflows/laravel-build-and-test.yml@main
    if: github.event.pull_request.draft == false
    with:
      php-version: '8.3'
